server:
  port: 8765
spring:
  application:
    name: gateway
zuul:
  sensitive-headers: [Authorization, Set-Cookie]
  ignored-services: "*"
  routes:
    api:
      path: /api/**
      service-id: api
      strip-prefix: true
